docs_path: ./docs
chunk_size: 1000
chunk_overlap: 200
embedding_model: all-MiniLM-L6-v2
llm_model_name: togethercomputer/RedPajama-INCITE-7B-Instruct
llm_auto_download: true
top_k: 4
vectorstore_path: ./chromadb
history_dir: ./history
